### PR TITLE
Update boot2docker.iso to v1.8.2

### PR DESCRIPTION
**Pull request by zchee**
Official boot2docker repository has been released 1.8.2.
https://github.com/boot2docker/boot2docker/releases/tag/v1.8.2

However, https://github.com/timfallmk/boot2docker/releases/download/v1.8.1/boot2docker.iso are custom boot2docker.iso ?
Or, update 1.8.1 only?
If this url is customized, Would you tell me what you did customize points?.
# 

PS,
@nathanleclaire and Docker Machine team has been started xhyve binding `docker-machine` project.
See https://github.com/nathanleclaire/machine/pull/3 and https://github.com/nathanleclaire/docker-machine-xhyve.
and, I started rewrite old https://github.com/docker/machine/pull/1358 PR.

I interested your https://github.com/ailispaw/xhyvectl and more than xhyve involved repository.
Thank you again for the your idea.

Regards,
Thanks.

### CODE REVIEW

**Comment by ailispaw** [comment]
@zchee Thank you for your PR.
The original boot2docker.iso causes a crash on boot because of Parallels Tools.
So we comment out the script for Parallels Tools in the custom boot2docker.iso.
https://github.com/ailispaw/boot2docker/commit/9a59e50c1e6df4b6e29ac82ebf67f912035308d6
https://github.com/ailispaw/boot2docker/pull/1
https://github.com/ailispaw/boot2docker/pull/2

**Comment by zchee** [comment]
@ailispaw Oh...
I'm not yet seen well, but this is the cause of Parallel side...?

For now, It seems no choice but to make a custom iso until the resolve problem...

**Comment by ailispaw** [comment]
@zchee I'm not sure what happens exactly.
The Parallels guy said the Parallels script won't run under the other hypervisor except Parallels,
however, it happens and it works well without Parallels Tools so far.

**Comment by zchee** [comment]
@ailispaw Now, possible run xhyve use docker-machine.
https://github.com/zchee/docker-machine-xhyve

Then, using ISO do not comment out https://github.com/zchee/boot2docker-legacy/blob/xhyve/rootfs/rootfs/bootscript.sh#L106
but, works fine.
Hmm...

**Comment by ailispaw** [comment]
@zchee Congratulations!

Is that the latest master of boot2docker?
It's interesting.

**Comment by ailispaw** [comment]
Now it seems to work fine with Docker v1.8.3.
Closing.
Thanks.

**Comment by ailispaw** [comment]
It seems just an accident.
https://github.com/boot2docker/boot2docker/pull/1074

**Comment by timfallmk** [comment]
Thanks guys!

**Pull request closed without merging**
